CREATE DATABASE nodedbcrud;

USE nodedbcrud;

CREATE TABLE customer(
    id INT(6) UNSIGNED AUTO_INCREMET PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    phone VARCHAR(15)
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL
);

SHOW TABLES;

DESCRIBE customer;